version: "3.9"
services:
    frontend:
        build:
            context: .
            dockerfile: Configs/Docker/frontend.Dockerfile

        ports:
            - "4200:4200"

        depends_on:
            - backend

    backend:
        build:
            context: .
            dockerfile: Configs/Docker/backend.Dockerfile

        env_file:
            - Configs/Docker/database.env
            - Configs/Docker/backend.env

        ports:
            - "5000:5000"

        depends_on:
            - database

    database:
        build:
            context: .
            dockerfile: Configs/Docker/database.Dockerfile

        env_file: Configs/Docker/database.env

        ports:
            - "1433:1433"
