version: "3.9"
services:
    frontend:
        build: Frontend
        depends_on:
            - backend

    backend:
        build: Backend
        depends_on:
            - database

    database:
        build: Database
